### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by proyb6** [reiswindy/mallofneeds#1]
Thanks for making a game, however, I won't know how the app look like until I spending hours to compile leading to an error on Ubuntu 16.04 using CRSFML installation approach 1:
```
./mallofneeds: symbol lookup error: /home/test/crsfml/voidcsfml/libvoidcsfml-system.so.2.5: undefined symbol: _ZTVN2sf17MemoryInputStreamE
```

**Comment by reiswindy** [comment]
Hi, make sure you run `app` instead of `mallofneeds`. I still need to make a guide on how to run this.

**Comment by reiswindy** [comment]
What's your SFML version? This seems to be a mismatch between your installed SFML version and the generated code from CrSFML. If you've updated SFML, make sure you re-generate the code for CrSFML or reinstall it.
